### ISSUE TITLE
Divide precompiled files for VT1 and VT2

### ISSUE THREAD

**Issue by Azumgi** [Vermintide-Mod-Framework/Vermintide-Mod-Builder#1]
Sometimes modders have to switch between VT1 and VT2 when compiling mods, and it's very frustrating to recompile everything every time. The compilation time can reach up to 5 mins for the mods working with shaders. Dividing precompiled files would be a good idea.

**Comment by unshame** [comment]
Do you mean separating the temp folder? Yeah, that seems like a good idea.

**Comment by unshame** [comment]
20960fc562a91ed9d309e3dafe216d9829acd26b

**Comment by Azumgi** [comment]
Thanks!
